// Mock car data
const mockCars = [
    {
      id: 1,
      name: "Model S",
      brand: "Tesla",
      price: 89990,
      fuelType: "Electric",
      seatingCapacity: 5,
      year: 2023,
      mileage: "396 mi range",
      image:
        "https://images.unsplash.com/photo-1617788138017-80ad40651399?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80",
      transmission: "Automatic",
      engine: "Dual Motor",
      color: "Pearl White",
      features: [
        "Autopilot",
        "Full Self-Driving Capability",
        "Premium Interior",
        "Ultra High Fidelity Sound",
        "Heated Seats",
        "Glass Roof",
        "Wireless Charging",
        "Premium Connectivity",
      ],
      description:
        "The Tesla Model S is an all-electric five-door liftback sedan produced by Tesla, Inc. The Model S features a dual motor all-wheel drive setup and is known for its long range and high performance.",
    },
    {
      id: 2,
      name: "Civic",
      brand: "Honda",
      price: 22550,
      fuelType: "Petrol",
      seatingCapacity: 5,
      year: 2023,
      mileage: "36 mpg",
      image:
        "https://imgd.aeplcdn.com/664x374/n/cw/ec/27074/civic-exterior-right-front-three-quarter-148155.jpeg?q=80",
      transmission: "CVT",
      engine: "2.0L 4-Cylinder",
      color: "Cosmic Blue",
      features: [
        "Honda Sensing Suite",
        "Apple CarPlay Integration",
        "Android Auto Integration",
        "Multi-Angle Rearview Camera",
        "Automatic Climate Control",
        "Push Button Start",
        "LED Headlights",
        "Smart Entry",
      ],
    },
    {
      id: 3,
      name: "X5",
      brand: "BMW",
      price: 61600,
      fuelType: "Diesel",
      seatingCapacity: 7,
      year: 2023,
      mileage: "26 mpg",
      image:
        "https://images.unsplash.com/photo-1580273916550-e323be2ae537?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1964&q=80",
      transmission: "8-Speed Automatic",
      engine: "3.0L 6-Cylinder",
      color: "Alpine White",
      features: [
        "xDrive All-Wheel Drive",
        "Live Cockpit Professional",
        "Panoramic Moonroof",
        "Harman Kardon Surround Sound",
        "Heated Front Seats",
        "Parking Assistant Plus",
        "Head-Up Display",
        "Wireless Charging",
      ],
    },
    {
      id: 4,
      name: "Camry",
      brand: "Toyota",
      price: 25945,
      fuelType: "Petrol",
      seatingCapacity: 5,
      year: 2023,
      mileage: "32 mpg",
      image:
        "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974&q=80",
      transmission: "8-Speed Automatic",
      engine: "2.5L 4-Cylinder",
      color: "Midnight Black",
      features: [
        "Toyota Safety Sense 2.5+",
        "Apple CarPlay & Android Auto",
        "Amazon Alexa Compatible",
        "Dual-Zone Automatic Climate Control",
        "Smart Key System",
        "LED Headlights",
        "Blind Spot Monitor",
        "Qi Wireless Charging",
      ],
    },
    {
      id: 5,
      name: "E-Class",
      brand: "Mercedes",
      price: 56750,
      fuelType: "Petrol",
      seatingCapacity: 5,
      year: 2023,
      mileage: "25 mpg",
      image:
        "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
      transmission: "9-Speed Automatic",
      engine: "2.0L 4-Cylinder Turbo",
      color: "Obsidian Black",
      features: [
        "MBUX Infotainment System",
        "Burmester Surround Sound",
        "Heated Front Seats",
        "Panorama Roof",
        "Active Parking Assist",
        "Blind Spot Assist",
        "LED Headlamps",
        "Wireless Charging",
      ],
    },
    {
      id: 6,
      name: "Mustang",
      brand: "Ford",
      price: 27770,
      fuelType: "Petrol",
      seatingCapacity: 4,
      year: 2023,
      mileage: "24 mpg",
      image:
        "https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
      transmission: "6-Speed Manual",
      engine: "2.3L EcoBoost",
      color: "Race Red",
      features: [
        "SYNC 3",
        "Apple CarPlay & Android Auto",
        "FordPass Connect",
        "Selectable Drive Modes",
        "LED Headlamps",
        "Reverse Sensing System",
        "Dual-Zone Electronic Climate Control",
        "Track Apps",
      ],
    },
    {
      id: 7,
      name: "Sonata",
      brand: "Hyundai",
      price: 24950,
      fuelType: "Hybrid",
      seatingCapacity: 5,
      year: 2023,
      mileage: "52 mpg",
      image:
        "https://imgd.aeplcdn.com/664x374/cw/cars/discontinued/hyundai/sonata-2011-2015.jpg?q=80",
      transmission: "6-Speed Automatic",
      engine: "2.0L 4-Cylinder Hybrid",
      color: "Hampton Gray",
      features: [
        "Hyundai SmartSense",
        "Apple CarPlay & Android Auto",
        "Bluelink Connected Car System",
        "Hands-Free Smart Trunk",
        "Heated Front Seats",
        "Dual Automatic Temperature Control",
        "Proximity Key with Push Button Start",
        "Bose Premium Audio",
      ],
    },
    {
      id: 8,
      name: "Sportage",
      brand: "Kia",
      price: 25990,
      fuelType: "Petrol",
      seatingCapacity: 5,
      year: 2023,
      mileage: "28 mpg",
      image:
        "https://images.unsplash.com/photo-1583267746897-2cf415887172?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
      transmission: "Automatic",
      engine: "2.5L 4-Cylinder",
      color: "Gravity Gray",
      features: [
        "Kia Drive Wise",
        "Apple CarPlay & Android Auto",
        "UVO Link",
        "Smart Power Liftgate",
        "Panoramic Sunroof",
        "Wireless Phone Charger",
        "Harman Kardon Premium Audio",
        "Smart Cruise Control",
      ],
    },
    {
      id: 9,
      name: "Altima",
      brand: "Nissan",
      price: 24550,
      fuelType: "Petrol",
      seatingCapacity: 5,
      year: 2023,
      mileage: "31 mpg",
      image:
        "https://images.unsplash.com/photo-1580273916550-e323be2ae537?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1964&q=80",
      transmission: "CVT",
      engine: "2.5L 4-Cylinder",
      color: "Scarlet Ember",
      features: [
        "Nissan Safety Shield 360",
        "Apple CarPlay & Android Auto",
        "NissanConnect Services",
        "Intelligent Climate Control",
        "Heated Front Seats",
        "Bose Premium Audio System",
        "Intelligent Around View Monitor",
        "ProPILOT Assist",
      ],
    },
    {
      id: 10,
      name: "A4",
      brand: "Audi",
      price: 39900,
      fuelType: "Petrol",
      seatingCapacity: 5,
      year: 2023,
      mileage: "29 mpg",
      image:
        "https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80",
      transmission: "7-Speed S tronic",
      engine: "2.0L 4-Cylinder TFSI",
      color: "Mythos Black",
      features: [
        "Audi pre sense",
        "MMI Navigation plus",
        "Audi virtual cockpit",
        "Bang & Olufsen 3D Premium Sound System",
        "Audi phone box",
        "Heated Front Seats",
        "Audi drive select",
        "Parking system plus",
      ],
    },
    {
      id: 11,
      name: "Model 3",
      brand: "Tesla",
      price: 46990,
      fuelType: "Electric",
      seatingCapacity: 5,
      year: 2023,
      mileage: "358 mi range",
      image:
        "https://images.unsplash.com/photo-1560958089-b8a1929cea89?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80",
      transmission: "Automatic",
      engine: "Dual Motor",
      color: "Deep Blue Metallic",
      features: [
        "Autopilot",
        '15" Touchscreen',
        "Premium Interior",
        "Glass Roof",
        "Wireless Charging",
        "Premium Audio",
        "Heated Front & Rear Seats",
        "Navigation",
      ],
    },
    {
      id: 12,
      name: "Accord",
      brand: "Honda",
      price: 26520,
      fuelType: "Hybrid",
      seatingCapacity: 5,
      year: 2023,
      mileage: "48 mpg",
      image:
        "https://images.unsplash.com/photo-1630990325544-58e7ed0d18ea?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
      transmission: "CVT",
      engine: "2.0L 4-Cylinder Hybrid",
      color: "Modern Steel",
      features: [
        "Honda Sensing Suite",
        "Wireless Apple CarPlay & Android Auto",
        "Head-Up Display",
        "Wireless Phone Charger",
        "Heated & Ventilated Front Seats",
        "Bose Premium Sound System",
        "Wi-Fi Hotspot",
        "Low-Speed Braking Control",
      ],
    },
    {
      id: 13,
      name: "Q5",
      brand: "Audi",
      price: 43500,
      fuelType: "Petrol",
      seatingCapacity: 5,
      year: 2023,
      mileage: "25 mpg",
      image:
        "https://images.unsplash.com/photo-1612825173281-9a193378527e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1199&q=80",
      transmission: "7-Speed S tronic",
      engine: "2.0L 4-Cylinder TFSI",
      color: "Navarra Blue",
      features: [
        "quattro all-wheel drive",
        "Audi virtual cockpit plus",
        "MMI Navigation plus",
        "Bang & Olufsen 3D Premium Sound System",
        "Panoramic sunroof",
        "Audi phone box",
        "Heated front seats",
        "Audi pre sense city",
      ],
    },
    {
      id: 14,
      name: "Tucson",
      brand: "Hyundai",
      price: 26450,
      fuelType: "Petrol",
      seatingCapacity: 5,
      year: 2023,
      mileage: "29 mpg",
      image:
        "https://imgd.aeplcdn.com/1056x594/n/dkalcva_1596121.jpg?q=80",
      transmission: "8-Speed Automatic",
      engine: "2.5L 4-Cylinder",
      color: "Amazon Gray",
      features: [
        "Hyundai SmartSense",
        "Apple CarPlay & Android Auto",
        "Bluelink Connected Car System",
        "Panoramic Sunroof",
        "Hands-Free Smart Liftgate",
        "Wireless Device Charging",
        "Bose Premium Audio",
        "Digital Key",
      ],
    },
    {
      id: 15,
      name: "CX-5",
      brand: "Mazda",
      price: 26700,
      fuelType: "Petrol",
      seatingCapacity: 5,
      year: 2023,
      mileage: "30 mpg",
      image:
        "https://images.unsplash.com/photo-1626668893632-6f3a4466d22f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1172&q=80",
      transmission: "6-Speed Automatic",
      engine: "2.5L 4-Cylinder",
      color: "Soul Red Crystal",
      features: [
        "i-Activsense Safety Features",
        "Apple CarPlay & Android Auto",
        "Mazda Connect Infotainment",
        "Bose 10-Speaker Audio",
        "Power Liftgate",
        "Heated Front Seats",
        "Leather-Trimmed Seats",
        "Dual-Zone Climate Control",
      ],
    },
    {
      id: 16,
      name: "Wrangler",
      brand: "Jeep",
      price: 29995,
      fuelType: "Petrol",
      seatingCapacity: 5,
      year: 2023,
      mileage: "22 mpg",
      image:
        "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
      transmission: "8-Speed Automatic",
      engine: "3.6L V6",
      color: "Firecracker Red",
      features: [
        "Command-Trac 4x4 System",
        "Uconnect 4 with 7-inch Display",
        "Apple CarPlay & Android Auto",
        "Removable Doors",
        "Fold-Down Windshield",
        "Wash-Out Interior",
        "Alpine Premium Audio",
        "SiriusXM Guardian",
      ],
    },
    {
      id: 17,
      name: "Sorento",
      brand: "Kia",
      price: 29990,
      fuelType: "Hybrid",
      seatingCapacity: 7,
      year: 2023,
      mileage: "37 mpg",
      image:
        "https://upload.wikimedia.org/wikipedia/commons/9/93/Kia_Sorento_Hybrid_EX_%28IV%29_%E2%80%93_f_02112024.jpg",
      transmission: "6-Speed Automatic",
      engine: "1.6L Turbocharged Hybrid",
      color: "Glacial White Pearl",
      features: [
        "Kia Drive Wise",
        "Apple CarPlay & Android Auto",
        "UVO Link",
        "Bose Premium Sound",
        "Panoramic Sunroof",
        "Wireless Phone Charger",
        "Smart Power Liftgate",
        "Highway Driving Assist",
      ],
    },
    {
      id: 18,
      name: "Pathfinder",
      brand: "Nissan",
      price: 34640,
      fuelType: "Petrol",
      seatingCapacity: 8,
      year: 2023,
      mileage: "23 mpg",
      image:
        "https://images.unsplash.com/photo-1609521263047-f8f205293f24?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
      transmission: "9-Speed Automatic",
      engine: "3.5L V6",
      color: "Boulder Gray",
      features: [
        "Nissan Safety Shield 360",
        "ProPILOT Assist",
        "Wireless Apple CarPlay",
        "Android Auto",
        "Tri-Zone Climate Control",
        "Panoramic Moonroof",
        "Bose Premium Audio",
        "Motion Activated Liftgate",
      ],
    },
    {
      id: 19,
      name: "Outback",
      brand: "Subaru",
      price: 28395,
      fuelType: "Petrol",
      seatingCapacity: 5,
      year: 2023,
      mileage: "33 mpg",
      image:
        "https://images.unsplash.com/photo-1626668893632-6f3a4466d22f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1172&q=80",
      transmission: "CVT",
      engine: "2.5L 4-Cylinder",
      color: "Crystal White Pearl",
      features: [
        "EyeSight Driver Assist Technology",
        "Symmetrical All-Wheel Drive",
        "STARLINK Multimedia",
        "Apple CarPlay & Android Auto",
        "Power Rear Gate",
        "Heated Front Seats",
        "Harman Kardon Premium Audio",
        "X-MODE with Hill Descent Control",
      ],
    },
    {
      id: 20,
      name: "XC60",
      brand: "Volvo",
      price: 43450,
      fuelType: "Hybrid",
      seatingCapacity: 5,
      year: 2023,
      mileage: "57 MPGe",
      image:
        "https://akm-img-a-in.tosshub.com/indiatoday/images/story/202111/volvo.jpg?size=690:388",
      transmission: "8-Speed Automatic",
      engine: "2.0L 4-Cylinder Plug-in Hybrid",
      color: "Denim Blue",
      features: [
        "City Safety Collision Avoidance",
        "Pilot Assist",
        "Sensus Navigation",
        "Harman Kardon Premium Sound",
        "Panoramic Moonroof",
        "Wireless Phone Charging",
        "Four-Zone Climate System",
        "Hands-Free Tailgate",
      ],
    },
  ]
  
  // Function to fetch cars
  export const fetchCars = async () => {
    // Simulate API call delay
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve(mockCars)
      }, 1000)
    })
  }
  
  // Function to fetch car by ID
  export const fetchCarById = async (id) => {
    // Simulate API call delay
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        const car = mockCars.find((car) => car.id === id)
        if (car) {
          resolve(car)
        } else {
          reject(new Error("Car not found"))
        }
      }, 500)
    })
  }
  